ALTER TYPE "AiIntent" ADD VALUE IF NOT EXISTS 'AI_CHAT';
ALTER TYPE "AiIntent" ADD VALUE IF NOT EXISTS 'GENERATE_TEST';
ALTER TYPE "AiIntent" ADD VALUE IF NOT EXISTS 'SUGGEST_RUBRIC';
ALTER TYPE "AiIntent" ADD VALUE IF NOT EXISTS 'TRANSLATE_WORD';
ALTER TYPE "AiIntent" ADD VALUE IF NOT EXISTS 'TRANSLATE_SENTENCE';
